attributes:
  uca_openstack_release:
    value: 'liberty'
    label: 'UCA OpenStack Release'
    description: 'This is the named release for the UCA packages (kilo, liberty, etc)'
    weight: 25
    type: "text"
